package view;

import database.dao.CounselorDAO;
import database.dao.impl.CounselorDAOImpl;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Counselor;

public class LoginPage extends javax.swing.JFrame {

    private List<Counselor> counselors;

    private CounselorDAO counselorDAO = new CounselorDAOImpl();

    private String desktopLanguage, desktopCountry;

    private Properties prop;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        
        /* Set the windows look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();
        // load users
        counselors = counselorDAO.getAllCounselors();

        this.counselors = counselorDAO.getAllCounselors();
        this.desktopLanguage = Locale.getDefault().getLanguage();
        this.desktopCountry = Locale.getDefault().getDisplayCountry();

        // load language properties
        try (InputStream input = new FileInputStream("languages.properties")) {

            prop = new Properties();

            // load a properties file
            prop.load(input);

            input.close();

        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        if(desktopCountry.equalsIgnoreCase("United States")) {
            desktopLanguage = "en";
        }
        // use Deutschland if Germany not worked
        else if(desktopCountry.equalsIgnoreCase("Germany")) {
            desktopLanguage = "de";
        }
        else if(desktopCountry.equalsIgnoreCase("México")) {
            desktopLanguage = "es";
        } else {
            desktopLanguage = "en";
        }
        
        if(!desktopLanguage.equalsIgnoreCase("en") 
                && !desktopLanguage.equalsIgnoreCase("de")
                && !desktopLanguage.equalsIgnoreCase("es")) {
            desktopLanguage = "en";
        }
        
        
        
        // change language of the UI components
        labelTopic.setText(prop.getProperty(desktopLanguage + ".login"));
        lblPin.setText(prop.getProperty(desktopLanguage + ".pin"));
        lblPassword.setText(prop.getProperty(desktopLanguage + ".password"));
        lblUsername.setText(prop.getProperty(desktopLanguage + ".username"));
        btnClear.setText(prop.getProperty(desktopLanguage + ".clear"));
        btnLogin.setText(prop.getProperty(desktopLanguage + ".login"));
        
        

        // start thread for the time
        new Thread() {

            @Override
            public void run() {
                while (true) {
                    LocalDateTime now = LocalDateTime.now();
                    DateTimeFormatter format = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
                    lblUserTime.setText(now.format(format));

                    // setting time for the main office 
                    ZonedDateTime nowInMainOffice = ZonedDateTime.now(ZoneId.of("America/New_York"));
                    lblMainOfficeTime.setText(nowInMainOffice.format(format));
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }.start();
    }

    private void clearTexts() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtPin.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        labelTopic = new javax.swing.JLabel();
        txtPin = new javax.swing.JPasswordField();
        lblPin = new javax.swing.JLabel();
        lblMainOfficeTime = new javax.swing.JLabel();
        lblUserTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appointment Manager");
        setResizable(false);

        lblUsername.setText("User Name");

        lblPassword.setText("Password");

        btnLogin.setText("Login");
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUsername.setText("admin");

        btnClear.setText("Clear");
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtPassword.setText("admin");

        labelTopic.setBackground(new java.awt.Color(32, 123, 198));
        labelTopic.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTopic.setForeground(new java.awt.Color(102, 102, 102));
        labelTopic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTopic.setText("Login");

        txtPin.setText("1234");

        lblPin.setText("PIN No.");

        lblMainOfficeTime.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        lblMainOfficeTime.setText("Main Office Time");

        lblUserTime.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        lblUserTime.setText("Your Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMainOfficeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserTime, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addComponent(labelTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btnClear)
                                .addGap(41, 41, 41)
                                .addComponent(btnLogin))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername)
                                    .addComponent(lblPassword)
                                    .addComponent(lblPin))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword)
                                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMainOfficeTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUserTime)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPin)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnClear))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // clear the text fields
        clearTexts();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        String pin = txtPin.getText().trim();

        if (username.isEmpty() || password.isEmpty() || pin.isEmpty()) {
            String erroMsg = prop.getProperty(desktopLanguage + ".empty_cred");
            JOptionPane.showMessageDialog(this, erroMsg);
            helper.Logger.errorLogin(erroMsg, username, password, pin);
        } else {
            Counselor user = null;
            for (Counselor cr : counselors) {
                if (cr.isAuthenticated(username, password, pin)) {
                    user = cr;
                    break;
                }
            }
            if (user == null) {
                // login failed
                String erroMsg = prop.getProperty(desktopLanguage + ".wrong_cred");
                JOptionPane.showMessageDialog(this, erroMsg);
                helper.Logger.errorLogin(erroMsg, username, password, pin);
            } else {
                // login success
                this.setVisible(false);
                HomePage.getInstance().login(user);
                helper.Logger.successLogin(user);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTopic;
    private javax.swing.JLabel lblMainOfficeTime;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblUserTime;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPin;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
