package view;

import database.dao.APTtypeDAO;
import database.dao.AppointmentDAO;
import database.dao.CounselorDAO;
import database.dao.impl.APTtypeDAOImpl;
import database.dao.impl.AppointmentDAOImpl;
import database.dao.impl.CounselorDAOImpl;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.APTType;
import model.Appointment;
import model.Counselor;

public class ReportPage extends javax.swing.JFrame {

    private DefaultComboBoxModel dcbmAptTypes, dcbmCounselors;

    private List<Appointment> appointments;

    private static AppointmentDAO appointmentDAO = new AppointmentDAOImpl();
    private static APTtypeDAO aPTtypeDAO = new APTtypeDAOImpl();
    private static CounselorDAO counselorDAO = new CounselorDAOImpl();

    /**
     * Creates new form ReportPage
     */
    public ReportPage() {
        initComponents();
        this.dcbmCounselors = (DefaultComboBoxModel) cbxCounselors.getModel();
        this.dcbmAptTypes = (DefaultComboBoxModel) cbxAptTypes.getModel();

        this.appointments = appointmentDAO.getAllAppointments();

        // popup combo boxes
        List<APTType> allAPTTypes = aPTtypeDAO.getAllAPTTypes();
        for (APTType apt : allAPTTypes) {
            dcbmAptTypes.addElement(apt);
        }

        List<Counselor> allCounselors = counselorDAO.getAllCounselors();
        for (Counselor cr : allCounselors) {
            dcbmCounselors.addElement(cr);
        }
    }

    private int countAptsByCounselor(Counselor counselor) {
        // USED: lambda
        return (int) appointments
                .stream()
                .filter(c -> c.getCounselor().equals(counselor))
                .count();
    }

    private int countAptsByAptType(APTType type) {
        // USED: lambda
        return (int) appointments
                .stream()
                .filter(c -> c.getType().equals(type))
                .count();
    }

    private int countAptsByState(String state) {
        // USED: lambda
        return (int) appointments
                .stream()
                .filter(c -> c.getPatient().getAddress().getState().equalsIgnoreCase(state))
                .count();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNoOfAptByType = new javax.swing.JTextField();
        cbxAptTypes = new javax.swing.JComboBox();
        cbxCounselors = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtNoOfAptByCounselors = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNoOfAptByState = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingActionHandler(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(32, 123, 198));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reports");

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setFocusPainted(false);
        btnHome.setOpaque(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Number of Appointments by Type");

        txtNoOfAptByType.setEditable(false);
        txtNoOfAptByType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNoOfAptByType.setText("0");

        cbxAptTypes.setFocusable(false);
        cbxAptTypes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAptTypesItemStateChanged(evt);
            }
        });

        cbxCounselors.setFocusable(false);
        cbxCounselors.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCounselorsItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Number of Appointments by Counselor");

        txtNoOfAptByCounselors.setEditable(false);
        txtNoOfAptByCounselors.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNoOfAptByCounselors.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Number of Appointments by State");

        txtNoOfAptByState.setEditable(false);
        txtNoOfAptByState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNoOfAptByState.setText("0");

        txtState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStateKeyReleased(evt);
            }
        });

        jLabel5.setText("Type the state here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNoOfAptByCounselors, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCounselors, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNoOfAptByType, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAptTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNoOfAptByState, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoOfAptByType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAptTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoOfAptByCounselors, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCounselors, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoOfAptByState, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
        HomePage.getInstance().navigate();
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void windowClosingActionHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingActionHandler
        
        HomePage.getInstance().navigate();
    }//GEN-LAST:event_windowClosingActionHandler

    private void cbxCounselorsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCounselorsItemStateChanged

        Counselor counselor = (Counselor) cbxCounselors.getSelectedItem();
        if (counselor == null) {
            txtNoOfAptByCounselors.setText("0");
        } else {
            int count = countAptsByCounselor(counselor);
            txtNoOfAptByCounselors.setText(count + "");
        }
    }//GEN-LAST:event_cbxCounselorsItemStateChanged

    private void cbxAptTypesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAptTypesItemStateChanged
        APTType type = (APTType) cbxAptTypes.getSelectedItem();
        if (type == null) {
            txtNoOfAptByType.setText("0");
        } else {
            int count = countAptsByAptType(type);
            txtNoOfAptByType.setText(count + "");
        }
    }//GEN-LAST:event_cbxAptTypesItemStateChanged

    private void txtStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStateKeyReleased
        String state = txtState.getText().trim();
        if (state.isEmpty()) {
            txtNoOfAptByState.setText("0");
        } else {
            int count = countAptsByState(state);
            txtNoOfAptByState.setText(count + "");
        }
    }//GEN-LAST:event_txtStateKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JComboBox cbxAptTypes;
    private javax.swing.JComboBox cbxCounselors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNoOfAptByCounselors;
    private javax.swing.JTextField txtNoOfAptByState;
    private javax.swing.JTextField txtNoOfAptByType;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
}
